<div class="message-view"></div>
<div class="message-list">
    <div class="left">
        <form id="formFindMessage" action="#">
            <span class="ui-icon ui-icon-search magnifier"></span>
            <input type="text" name="query" style="width: 16em" />
            <input type="submit" value="ok" /> &nbsp;&nbsp;&nbsp;
        </form>
    </div>
    <div class="aright">
        <?php if ($this->sent):?>
            <?php echo $this->ajax('Inbox', 'message/index', 2)?>
        <?php else:?>
            <?php echo $this->ajax('Sent', 'message/index/sent', 2)?>
        <?php endif?>
        <input type="button" class="message-new" value="<?php echo $this->translate('new')?>" />
    </div>
    <br />
    <?php if(count($this->data)):?>
    <table class="datatable messages">
        <tr>
            <th><input type="checkbox" id="message-all" /></th>
            <th><?php echo $this->translate('Name')?></th>
            <th></th>
            <th><?php echo $this->translate('Description')?></th>
            <th><?php echo $this->translate('Date')?></th>
        </tr>
        <?php foreach($this->data as $data): ?>
            <?php
                $readingStatus = null;
                if (!$data->read && !$this->sent) {
                    $readingStatus = "unread";
                }
            ?>
            <tr class="<?php echo $readingStatus?>">
                <td><input type="checkbox" class="childrens" name="messages[]" value="<?php echo $data->id?>" /></td>
                <td title="<?php echo $data->name?> <?php echo $data->email?>">
                    <div style="width: 120px; height: 15px; overflow: hidden; float: left;">
                        <?php echo $data->name?>
                    </div>
                </td>
                <td>
                    <?php if (isset($data->total) && $data->total > 0) :?>
                        (<?php echo $data->total?>)
                    <?php endif?>
                </td>
                <td><div style="width: 300px; height: 15px; overflow: hidden;"><?php echo strip_tags($data->description)?></div></td>
                <td nowrap="nowrap"><?php echo $this->date($data->created, true)?></td>
            </tr>
        <?php endforeach;?>
    </table>
    <br />
    <div class="left">
        <input type="button" id="message-delete" value="<?php echo $this->translate('delete')?>" />
    </div>
    <div id="message-page">
        <?php echo $this->paginationControl($this->data) ?>
    </div>
    <?php else:?>
        <p><?php echo $this->translate( "there are no records" );?></p>
    <?php endif;?>
</div>
<script type="text/javascript">
    $('#message-page a').click(function(){
        $(this).parents('.content').load(this.href);
        return false;
    });

    $('#message-delete').click(function(){
        var $this = $(this);
        var $messages = $('.messages').find('.childrens[checked=true]');
        if ($messages.length) {
            if (confirm('<?php echo $this->translate('want to delete?')?>')) {
                $.post('message/index/delete/sent/<?php echo $this->sent?>', $messages.serialize(), function(data){
                    $this.parents('.content').html(data);
                });
            }
        } else {
            alert('<?php echo $this->translate('Select one message')?>');
        }
    });

    $('.messages div').click(function(){
        var $this = $(this),
            id = $this.parents('tr').find('input').val();
        $('.message-view').load('message/index/view/id/' + id, function(){
            $('.message-list').hide();
            $('.message-view').show();
            $this.parents('.unread').removeClass('unread');
        });
        return false;
    });

    $('.message-new').click(function(){
        
        $('.message-view').load('message/index/form', function(){
            $('.message-list').hide();
            $('.message-view').show();
        });
        return false;
    });

    $('#message-all').click(function(){
        if (this.checked == true) {
            $('.messages').find('.childrens').attr('checked', true);
        } else {
            $('.messages').find('.childrens').attr('checked', false);
        }
    });
    
    $("#formFindMessage").submit(function() {
        var url = 'message/index/index/?';
        <?php if ($this->sent):?>
            url = 'message/index/sent/?'
        <?php endif;?>
		$(this).parents('.content').load(url + $(this).serialize());
        return false;
	});

    $('input[type=button], input[type=submit]').button();
</script>
<?php echo $this->title($this->title, '.message-list')?>